net.Receive("yayo_crusaderAppeared", function()
    chat.AddText(Color(0, 0, 0, 255), "OCCULT", Color(50, 50, 50, 255), "|", color_white, " A Crusader has breached the veil.")
    surface.PlaySound("placenta/radiokom2.wav")
end)
net.Receive("yayo_crusaderCooldown", function()
    chat.AddText(Color(0, 0, 0, 255), "OCCULT", Color(50, 50, 50, 255), "|", color_white, " A Crusader Potential has appeared!.")
end)
net.Receive("yayo_martyrCooldown", function()
    chat.AddText(Color(0, 0, 0, 255), "OCCULT", Color(50, 50, 50, 255), "|", color_white, " A Martyr Potential has appeared!.")
end)