net.Receive("yayo_YouAreObsession", function()
    print("You are obsession")
    surface.PlaySound("skinshape/obession_chosen.wav")
    chat.AddText(Color(255, 0, 0), "A Skinshape is obsessed with you!")
end)
net.Receive("yayo_ShapeNewObsession", function()
    local obs = net.ReadEntity()
    print("You have a new obsession: " .. obs:Nick())
    surface.PlaySound("skinshape/obession_chosen.wav")
    chat.AddText(Color(255, 0, 0), "Your obsession is " .. obs:Nick() .. " kill them for rewards!")
end)

net.Receive("yayo_ObsessionComplete", function()
    chat.AddText(Color(255, 0, 0), "You killed your obsession!")
end)