net.Receive("yayo.YouAreObession", function( len, ply )
    print("You are obsession")
    surface.PlaySound("skinshape/obession_chosen.wav")
end)
net.Receive("yayo.ShapeNewObsession", function()
    local obs = net.ReadString()
    print("You have a new obsession: " .. obs)
    surface.PlaySound("skinshape/obession_chosen.wav")
end)
